apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-helio-core
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helio-core
  template:
    metadata:
      labels:
        app: helio-core
    spec:
      containers:
        - name: helio-core
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
