apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-helio-core
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: helio-core
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
